### ISSUE TITLE
Support first-party isolation (FPI) without work-arounds

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/cookie-manager#1]
Currently, support for editing cookies with First Party Isolation is limited to the case where the cookie's first party domain is the same as the cookie's domain.

If firsrtPartyDomain-awareness is added to the cookies API (i.e. when https://bugzil.la/1381197 and/or https://bugzil.la/1362834 are fixed), then the add-on can be updated to support modification of cookies with firstPartyDomain, without work-arounds.

**Comment by oh-ren** [comment]
I believe it should be possible to implement this now (since FF59)? :+1:

**Comment by Rob--W** [comment]
@oh-ren Yes. But I'm scratching my head on how to implement this in the UI. With first-party isolation, every first-party domain gets their own cookie jar.

I could use the existing "cookie jar" filter for that (currently private browsing mode and container tabs), but that will quickly make the list of cookie jars very large, because the first party isolation is also within each container tab / private browsing session.

I was thinking of a treeview UI or something. I haven't received any requests from users on how they'd like to manage first-party cookies; suggestions are welcome.

**Comment by oh-ren** [comment]
Hmm, I'll give that a thought.

Have you ever considered to incorporate management of local storage as well?

Thanks for your quality contributions allround btw :wink:  :+1:
