### ISSUE TITLE
Feature Request: Allow GitHub Wiki

### ISSUE THREAD

**Issue by Grossdm** [Rob--W/cookie-manager#10]
That's pretty much it.
Unless I somehow completely missed it, there is no wiki.
Users could help each other this way - perhaps saving the developer's time!

Doug®

**Comment by Rob--W** [comment]
There is no wiki. Pull requests to extend the content of `README.md` are
welcome.

There are some poorly documented features, such as the whitelist.

**Comment by Grossdm** [comment]
I actually noticed that there was no wiki. :grinning: 
It was simply a request to allow it.
Denial accepted humbly.

Doug®
