### ISSUE TITLE
Going back closes Firefox

### ISSUE THREAD

**Issue by kioth** [Rob--W/cookie-manager#12]
On Android, going back closes Firefox. It should close the current tab and go back to the previous tab.

**Comment by Rob--W** [comment]
Why do you have the expectation that "going back" should close the current tab? If there is no "previous page", then Firefox's default behavior is to exit the app.

To change this default behavior, I could open a temporary tab, and then navigate to the cookie manager from that tab. When the tab is navigated to again ("go back"), then I would close the tab. This is doable, but I wonder whether I should implement this.

**Comment by Rob--W** [comment]
I usually disable the cookie manager by default, and when I want to use it, I go to Add-ons, then enable the add-on.

If the add-on is configured to not open the cookie manager upon start-up (or if you have closed the cookie manager), then I click on the "Options" button at the "Cookie Manager" settings to open the Cookie Manager.

In both cases, "going back" will close the tab and show the previous tab (the add-ons page). Does this help?

**Comment by kioth** [comment]
@Rob--W yes, thank you. I will do that from now on ;)
