### ISSUE TITLE
please add a "LICENSE" file

### ISSUE THREAD

**Issue by Zig-03** [Rob--W/cookie-manager#17]
please add a "LICENSE" file so that people know what & how they can use the source code you provide, thank you.
 
_fingers crossed for GPLv3. :3_

**Comment by Rob--W** [comment]
[MPL-2.0](https://www.mozilla.org/MPL/2.0/)

**Comment by Zig-03** [comment]
thanks for the link, my suggestion though was to make it public/visible to everyone by creating this file (as it's usually done).

Thank you.
