### ISSUE TITLE
Options page address

### ISSUE THREAD

**Issue by juneyourtech** [Rob--W/cookie-manager#22]
What is the URL bar address of the options page?

Is the add-on a WebExtension?

**Comment by Rob--W** [comment]
Yes, it is a WebExtension. There is no separate options page; the one and only page in the cookie manager is the cookie manager page. It also shows a checkbox that you can use to toggle whether the cookie manager should be shown on startup.

https://github.com/Rob--W/cookie-manager/blob/bc9d3798a69cb379eddeeceff9f086fe589d9c22/manifest_firefox.json#L16-L19

**Comment by juneyourtech** [comment]
> Yes, it is a WebExtension.

Oh, a pity. I was hoping for a cookie manager extension for Firefox and Firefox for Android up to and including 43.0, because that still supports cookie prompting via Cookie Prompter extension, and Cookie Whitelist for Fennec also allows editing/deleting permissions for a visited domain. On Firefox for Android, there is no built-in cookie manager UI, and about:permissions is missing, too.

**Comment by Rob--W** [comment]
I published

**Comment by juneyourtech** [comment]
Oh?

**Comment by Rob--W** [comment]
I pressed the wrong key, see edited comment.

**Comment by juneyourtech** [comment]
I've edited a comment with a question upthread.

**Comment by Rob--W** [comment]
Using Android 2.3 is also a big security risk. Hopefully you aren't using your phone for anything sensitive.

You could also try to create a cookie manager yourself that meets your use cases. My cookie manager's UI does currently not look "pretty", but it is functional and that is what I needed. Creating an add-on that is a glorified frontend to the internal cookie API is probably a reasonably small task. If it is expected to take a lot of time, then it might be more economic to buy a new phone with more up-to-date software.

Good luck with finding a solution that fits your needs!

**Comment by juneyourtech** [comment]
I'm [one of the 0.3%](https://www.androidpolice.com/2018/09/29/google-posts-septembers-android-platform-distribution-numbers-still-no-pie/) of Gingerbread users :)

I do not download apps from the Google Play Store, and I've mostly installed apps from the free / open-source F-Droid repository. Any browsing is done with Firefox or IceCat, with NoScript blocking most of the muck.

I do not use the default browser ("Internet"), and it usually has JavaScript and cookies turned off. Many of its certificates have become outdated, precluding visits to modern sites. The stock browser's rendering engine is also much older than the Gecko engine of either Firefox or IceCat. On Android 2.3, the most recent Firefox is v47.0.

I haven't created an add-on before, and I've twice modified an existing one. With the latter, I tried to change the wmlbrowser extension, which was made for very early versions of Fennec, to work on Firefox 38 or newer (up to v56.0), but the change didn't work.
