### ISSUE TITLE
month is missing from the date selector

### ISSUE THREAD

**Issue by R-Adrian** [Rob--W/cookie-manager#29]
where has "February" gone? an entire month is missing from this list...

![missing_february](https://user-images.githubusercontent.com/16319504/55278812-eb640800-5319-11e9-83dd-f9d06ea72ec4.png)

TY

**Comment by Rob--W** [comment]
Thanks for the report. I added a patch that fixed the issue for the next release (not scheduled yet).

As a work-around, either select the first "March". Or wait two days ;)

**Comment by Rob--W** [comment]
Finally published, as 1.6.
