### ISSUE TITLE
Firefox Add-on signing

### ISSUE THREAD

**Issue by amadeous** [Rob--W/cookie-manager#30]
My Firefox recently upgraded and your extension got disabled.

Their docs recommend to ask add-on maintainers to sign their extension.

Could you please consider it ? Thanks a lot for your marvelous add-on !
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by Rob--W** [comment]
Thanks for your report.

This was a bug in Firefox, and a work-around has been published. A permanent solution is in progress.
Please see https://support.mozilla.org/en-US/kb/add-ons-failing-install-firefox

**Comment by Bambr-name** [comment]
Hi Rob!
it is still doesn't work: I tried to setup addon from page 
https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/  
I got this error "Download failed. Please check your connection" but connection is fine.
Could you suggest how to make it work?

**Comment by Bambr-name** [comment]
Hi Rob!
it is still doesn't work: I tried to setup addon from page
https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/
I got this error "Download failed. Please check your connection" but connection is fine.
Could you suggest how to make it work?

p.s. xpinstall.signatures.required  is false, Firefox 54.0.1 (32-bit)

**Comment by Rob--W** [comment]
@Bambr-name Why are you using such an old version of Firefox?
Anyway, to fix the issue, install this add-on: https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-52-56/ (referenced via https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ ).

**Comment by Bambr-name** [comment]
Thank you A LOT!!!   It works!
