### ISSUE TITLE
Installation aborted because the add-on appears to be corrupt

### ISSUE THREAD

**Issue by Bambr-name** [Rob--W/cookie-manager#33]
Hi Rob!
I tried to install but got this error: Installation aborted because the add-on appears to be corrupt
Could you check it out?

screenshot https://i.imgur.com/DxJe5jC.png

Firefox Quantum 66.0.2 (64-bit)

**Comment by Rob--W** [comment]
This is not a bug with this add-on, but with your version of Firefox.
You should upgrade to the latest version of Firefox, which is currently at version 68.

The comments at #30 provide more details on why you're experiencing this issue.
