### ISSUE TITLE
By default, the Cookie Manager opens when the extension starts up. 

### ISSUE THREAD

**Issue by marjwyatt** [Rob--W/cookie-manager#34]
I recently added this extension on my Firefox Quantum (v68.0.1 64-bit) browser.  I've had it installed on my Firefox Developer (v69.0b9 64-bit) browser for a while and found it useful.  But, the behavior on the Quantum installation seems different.  

Every time I fire up Firefox Quantum, a separate tab opens for Cookie manager.  Every time I open Firefox Developer, it doesn't.  How do I change the default to activate a Cookie Manager window only on click?

**Comment by Rob--W** [comment]
The cookie manager (tab) has a checkbox with the label "Open the Cookie Manager when the extension starts up."

Have you tried unticking that checkbox?

**Comment by marjwyatt** [comment]
Yeah.  I just saw it this morning.  

Thank you for the quick answer to what turned out to be a silly question.
