### ISSUE TITLE
ALWAYS opens when the extension starts up

### ISSUE THREAD

**Issue by BoboSims** [Rob--W/cookie-manager#37]
I hav e Cookie Manager installed with the latest version of Firefox on my Win7 desktop. The only thing that changed recently, is that FF updated.

I always had the option "Open the Cookie Manager when the extension starts up." UNticked, and up until a few days ago, it worked like that perfectly. Cookie Manager wouldn't open until *I* told it to.

But now, since a few days, it ALWAYS opens when first opening my browser after boot-up. And the setting mentioned above is ALWAYS ticked. I can UNtick it, and it will hold for that session. But as soon as I reboot my system, it is ticked again! It annoys me to have to close that tab all the time, especially since I didn't ask it to be opened in the first place.

Anyone else encountering this issue? Anyone know what's up with this?

**Comment by Rob--W** [comment]
Are you using third-party software that . modifies your Firefox profile, such as CCleaner? I know of a similar report of dataloss due caused by CCleaner - https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/#comment-226930

Are you using Firefox Sync? If so, is there anything of interest in `about:sync-log` ?

Do you see any error message in the global console (ctrl-shift-j)?

**Comment by BoboSims** [comment]
Ah, that is nasty business. I've had CCleaner for so long, and it has never done that. But I remember seeing the "Firefox Internet Cache" setting recently, and thinking that it would be useful to keep that clean as well. In my opinion, this issue should not have been the consequence of that setting, but evidently it is. My problem has been solved by unticking that option in CCleaner.

Thank you so much for your help!

**Comment by bege10** [comment]
Thank you for leading me to this post. It is the same issue here, unchecking Internet Cache solves the issue.
That seems strange to me because these are the files listed by CCleaner at this entry:

> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\1mo1MZccdAstexKxWk8kMg==.ico	46 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\dcx+vwsORfzESNs0+r_uEw==.ico	1 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\E1x3_tNSG8Dd2EDhAfJ_1Q==.ico	10 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\FS65FAviMGxU4B0iDkfMpQ==.ico	1 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\HORfGWwW+7NmIg3fAbeesw==.ico	13 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\T3kJTgul_Peb5ePROHIacA==.ico	46 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\XF6AJxgxaeM49ZKQkkk3zA==.ico	1 KB
> C:\Users\bege\AppData\Local\Mozilla\Firefox\Profiles\487kit50.Quantum\jumpListCache\xxrnNq92UmEizZPIdQnbUQ==.ico	13 KB
> C:\Users\bege\AppData\Roaming\Mozilla\Firefox\Profiles\487kit50.Quantum\storage-sync-v2.sqlite-wal	513 KB
> C:\Users\bege\AppData\Roaming\Mozilla\Firefox\Profiles\487kit50.Quantum\storage-sync-v2.sqlite-shm	32 KB

Where does Cookie Manager store this option?

**Comment by BoboSims** [comment]
> Where does Cookie Manager store this option?

I'm sure it's not in the jumpListCache folder; those are all just icons. So, by as muc h - or as little - logic as I understand, that leaves only the last two files. Odd thing is, I have those storage-sync-vw.sqlite-etc files as well, but I don't use sync at all. So I'm suspecting that they aren't involved in this issue either.

**Comment by Rob--W** [comment]
The cookie manager stores preferences with the `browser.storage.sync` API, so that users who do use Sync to sync add-ons will have their preferences synced as well.

When you aren't logged in with Sync, the data is still saved locally, but never sent to the remote Sync backend.

The data is locally saved in storage-sync-v2.sqlite-shm and storage-sync-v2.sqlite-wal.

**Comment by BoboSims** [comment]
Which then means that CCleaner could've been more selective about what it cleans out. But that's not something anyone here can do anything about. Well, thanks for explaining that, Rob.

**Comment by bege10** [comment]
> The data is locally saved in storage-sync-v2.sqlite-shm and storage-sync-v2.sqlite-wal.

Thanks from me, too, for the explanation. So either unchecking "Firefox Internet Cache" as mentioned or adding the two files to the exceptions should do.

**Comment by bege10** [comment]
CCleaner 5.70 has fixed the issue. storage-sync-v2.sqlite-shm and storage-sync-v2.sqlite-wal are no longer being deleted.

**Comment by BoboSims** [comment]
> 
> 
> CCleaner 5.70 has fixed the issue. storage-sync-v2.sqlite-shm and storage-sync-v2.sqlite-wal are no longer being deleted.

GREAT. Thanks for the update, bege10.

**Comment by Rob--W** [comment]
FYI article from Mozilla support about this issue: https://support.mozilla.org/en-US/kb/ccleaner-deleting-firefox-extension-settings-firef
