### ISSUE TITLE
Import/export in standard formats

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/cookie-manager#4]
Follow-up to #2 : Add the ability to export/import cookies in a different format, such as Netscape's cookies.txt format: https://github.com/Rob--W/cookie-manager/issues/2#issuecomment-348712338

Netscape's cookies.txt format does not support as much fields as the import/export format (in JSON), so the import feature should also provide some way to fill in the missing fields.

**Comment by Lekensteyn** [comment]
@Jon-Dijk In https://github.com/Rob--W/cookie-manager/issues/2#issuecomment-349548625 you requested the ability to import Netscape-style cookie jars. Is this feature important to you? Currently I am looking at just exporting it for use in an external application.

**Comment by aletaziar** [comment]
Exporting it to Netscape-style cookies.txt would be helpful to me. A lot of external applications use this format.
