### ISSUE TITLE
import from cookies.txt

### ISSUE THREAD

**Issue by underhandedness** [Rob--W/cookie-manager#40]
Given a cookies.txt with header

`# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.`

provide a less thinky import of some or all contained cookies.

**Comment by underhandedness** [comment]
it's not clear to me why code markup was ignored.

**Comment by Rob--W** [comment]
Are you asking for a better user interface to help with selectively importing cookies from cookies.txt?
