### ISSUE TITLE
Some cookies can't be removed or edited even after multiple attempts to do so

### ISSUE THREAD

**Issue by ericmberg** [Rob--W/cookie-manager#43]
I have been using Cookie Manager since Jan. 2020 with great success.  (Environment: Dell Inspiron 15-7567 laptop running the latest version of 64-bit Windows 10 Professional and the latest version of 64-bit Firefox -- currently 88.0.  I'm attaching a screenshot showing the browser extension that are installed.)

![20210504_Firefox_browser_containers_Inspiron 15-7567](https://user-images.githubusercontent.com/17481496/117081281-703d5f00-acf4-11eb-8786-f8b87c1b9f50.jpg)
![20210504_Firefox_browser_add-ons_Inspiron 15-7567](https://user-images.githubusercontent.com/17481496/117081284-70d5f580-acf4-11eb-8522-8d4e3d7732a2.jpg)

However, starting a couple of months ago, Cookie Manager was no longer deleting all the cookies that I was trying to delete manually.  For example, if I wanted to delete all the cookies in a container, I would set the "Cookie Jar" field to one of my Firefox containers, click Search, click Select All, then click Delete Selected.  (If any of the cookies happen to be whitelisted, I get a prompt to unlock them, and I run Delete Selected again on the unlocked whitelisted cookies.)  All the cookies that are visible are now dimmed out to show that they are deleted.

At this point, when I click Search again, many of the cookies have been removed, but some still remain.  I haven't noticed any patterns in which cookies remain (e.g. it's not that they were all whitelisted cookies that I had unlocked.)  And, for the cookies that remain, if I try deleting them one by one, each one dims out, but then reappears after I click search.  Also, for the cookies that remain, if I use the Edit button and try to make some changes in the data fields and then click Save, the original cookie is still there in its unmodified state, and it has created a new duplicate of that cookie that does include my edits.

This doesn't only happen if I click Select All.  Even if I select cookies individually, or do a multi-select (click on one cookie and then drag the mouse pointed down to select adjacent cookies), I get the exact same problem.

Unlike one of the earlier bug reports, where Cookie Manager displays an error message for tabs that it can't delete, in my case, it just fails silently (no error message).

The only thing about my use of Firefox that might be unusual is that I have 4 Firefox windows open and a lot of tabs in each window -- in one of the windows, I have hundreds of tabs.  When I exit Firefox, I do so by killing its process using Task Manager.  Then, when I restart Firefox, all the tabs reappear but are blank -- the contents of a tab don't get loaded from the website until I click on it.  (That's how I can have hundreds of tabs open without having performance get very bad.)  

Some of the cookies that I'm trying to delete are associated with pages that I currently have loaded.  I don't know whether that's causing the problem.  However, I was using Cookie Manager in the same way (hundreds of tabs open and trying to delete cookies associated with loaded pages) during all of 2020 and at the start of 2021, and Cookie Manager didn't have any problems.

**Comment by Rob--W** [comment]
Did this start happening in Firefox 86? This is probably due to dynamic First-Party Isolation, aka "Total Cookie protection" (https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) (https://bugzilla.mozilla.org/show_bug.cgi?id=1686296). This feature is enabled when you've enabled Enhanced Tracking Protection (cross-site cookies), i.e. having the `network.cookie.cookieBehavior` preference set to `5`.

My Cookie Manager extensions is unable to delete cookies because extensions are unaware of this feature. Support for this feature is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1669716 . I'm the assignee to this bug (as a Firefox engineer), so I should be fixing this issue in any case...

**Comment by ericmberg** [comment]
Rob:

Thanks for your explanation, and for the very prompt response.  Yes, I do
have Enhanced Tracker Protection set to Strict (
network.cookie.cookieBehavior is set to 5), and the problem started
happening around the time that Firefox 86 was released.

So, if I understand correctly, there's nothing that I can do differently in
how I use Cookie Manager to solve the problem, and no change to the Cookie
Manager code that you can make to solve the problem until the Firefox API
is updated to allow cookie-manipulating extensions to work correctly when
Dynamic First-Party Isolation is turned on.

Is there anything that I need to do to update either the text or the status
of the bug that I filed in GitHub?

Thanks, and I'd again like to say that Cookie Manager is a great product.

Here's a user interface suggestion that you might keep in mind for future
implementation (or maybe it already works this way and I just don't know
how to do it): There's no way to refresh the view other than by clicking
the Search Cookies button at the top of the view, and if I have scrolled
down through many screens of cookies, then I have to do a lot of scrolling
back up to get to the Search Cookies button (and then probably scroll back
down through many screens of cookies).  One way to fix this would be to
make the "query-by-form" section of the UI static at the top of the screen,
and have only the rows of cookies be scrollable, rather than scrolling
everything but the six action buttons at the bottom of the screen.  Another
way to fix it would be to add a small "Refresh" button (which would do the
same thing as the Search Cookies button, but display the usual "refresh" or
"reload" icon) to the row of action buttons, since they are already always
visible.

/Eric

----------
Eric M. Berg
***@***.***
+1 650 539-4790

**Comment by Rob--W** [comment]
FYI: This should work now. I fixed the issue in Firefox 1 year ago, and added support for that in the cookie manager in https://github.com/Rob--W/cookie-manager/commit/a59ca9aa57d910abfb7890e2019547e9bb4d9afd
