### ISSUE TITLE
Cookie question -

### ISSUE THREAD

**Issue by deehill** [Rob--W/cookie-manager#46]
Hi Rob.

Looking over the cookie-manager app. I've got a couple of questions and thought I'd ping you to see if you might give me insight.

Say I have multiple TABs and each tab is running a url. If the urls are all of the same "domain" but different pages, how are the "cookies" from the urls tracked? If the url in say TAB1 changes ,and it changes the cookie, does this override the cookie previously changed?

I'm looking to try to create a modified extension that will allow me to monitor when a "cookie" changes in a given "TAB" and to then copy that cookie to another TAB, running another url. Both tabs would be running the same "domain"

thanks

-bruce

**Comment by Rob--W** [comment]
Cookies are not only keyed by domain and name, but also by the `path`. By default, the path is `/`, but you can set the path to something else (e.g. `/Rob--W/`, `/Rob--W/cookie-manager/` or `/Rob--W/cookie-manager/issues/` are possible paths for this page on Github).

You can see this helper method to see which parts of cookie contribute to the identity of a cookie: https://github.com/Rob--W/cookie-manager/blob/99d3c0936719fedcb8cf44066ff10e42084a7e9c/cookie-manager.js#L2689-L2705

**Comment by deehill** [comment]
Hi Rob.

Thanks for getting back to me.

So, to clarify. it should be doable to have an extension that will "pull"
the Cookie from Tab1/Url1 in a manner that I can then copy that Cookie to
Tab2/Url2 and then invoke the http+cookie process to generate the next/new
page.

thanks
-bruce

ps. I'm looking to test/do this as I'm looking to generate a test extension
that I can use to "test" multiple URLs across multiple Tabs. But every so
often, the app requires that I generate a new page for the recpatcha. I can
do what I want manually. I'm interested to figure out how I could do this
in a semi manual/auto process.

thanks again!

**Comment by Rob--W** [comment]
> I'm looking to test/do this as I'm looking to generate a test extension that I can use to "test" multiple URLs across multiple Tabs

A better solution for your use case is to use the Container Tabs feature of Firefox. Extensions can create new container tab identities using the `contextualIdentities` API (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities) and then open tabs with `browser.tabs.create({ url: "...", cookieStoreId: "firefox-container-1234" })` (where `firefox-container-1234` is obtained via the `contextualIdentities` API).
