### ISSUE TITLE
Oscar

### ISSUE THREAD

**Issue by Shadow88V** [Rob--W/cookie-manager#47]
Hi Rob 
A big request from an ordinary user.  Not all users think like you.  Can you imagine ?!  If you already got down to business and create something new, then personally I and a couple of million people, we will be very grateful to you for your help.  PLEASE ,WRITE THIS FUCKING MANUAL HOW TO INSTALL YOUR COOKIES MANAGER ON ANDROID MOBILE !!!  In simple human words, like for children.  Do 1, do 2, do 3, etc.  So I bought a new phone and what a person with two higher educations needs to do for me to use your cookie manager.  And most importantly, I repeat, the algorithm is step 1, step 2, step 3 ... ... 
Thank you so much Earthman!

Best,
Oscar

**Comment by Rob--W** [comment]
See my reply at #45 . The installation used to be much simpler, but it's currently much more involved because the set of easily installable extensions on mobile is limited.
