### ISSUE TITLE
Buggy private browsing cookie jar

### ISSUE THREAD

**Issue by git42leech** [Rob--W/cookie-manager#48]
Cookies from the private browsing cookie jar will be deleted if you restart the browser, you can not save them in private mode.
Exporting the cookie and importing after restarting works fine though.

`Cookie Manager Version 1.6`
`Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux`
`firefox-esr                                   78.15.0esr-1~deb11u1`

**Comment by Rob--W** [comment]
> Cookies from the private browsing cookie jar will be deleted if you restart the browser,

That is not a bug, but a feature of the browser.

If you'd like to have a cookie jar that is isolated from the main cookie jar, use container tabs instead - see https://support.mozilla.org/en-US/kb/containers

**Comment by git42leech** [comment]
You have every right to think so and close the issue but there is nothing wrong with having persistent cookies in private mode, containers do not solve this bug.

The cookie manager could automatically load the private cookies.
