### ISSUE TITLE
Two partially overlapping date picker interfaces

### ISSUE THREAD

**Issue by laniakea64** [Rob--W/cookie-manager#52]
**Environment**
Firefox 108.0.1
new profile
Cookie Manager 1.7

**Steps to reproduce**

1) install Cookie Manager from https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager

2) get some cookies, e.g. by going to github.com

3) click Search Cookies to display the cookies

4) click Edit for one of the cookies

5) under "Expiration", click the text "Expiry date:"

**Expected results:** I think a date picker (and only one date picker interface) should come up?

**Actual results:**

Two date picker interfaces come up, one partially on top of the other, and interfere with each other.  Looks like one is Firefox native date picker and the other is from `datetime-polyfill.js`.

Is the polyfill intended to be active here, even though [Firefox has native support for `<input type="datetime-local">` since version 93](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#browser_compatibility)?  I did find [this code](https://github.com/Rob--W/cookie-manager/blob/c1d5f0597bf3347f11a9cf4999db12a30079ea27/datetime-local-polyfill.js#L2-L11) and https://github.com/Rob--W/cookie-manager/issues/14 in searching, but that issue seems too old to be directly related to this behavior or speak to current intent on current Firefox versions?

**Comment by Rob--W** [comment]
Thanks for your report. I committed the patch over a year ago, but published an update just now.
