### ISSUE TITLE
Unable to import cookies with unspecified sameSite in Firefox

### ISSUE THREAD

**Issue by TheDcoder** [Rob--W/cookie-manager#53]
The extension currently encounters an unhandled exception in Firefox when trying to import cookies with `sameSite` set to `unspecified`, which seems to be the default value for all cookies, at-least in Chrome where I exported cookies. Replacing `unspecified` with `no_restriction` works around the issue as it's one of the valid values in Firefox and also the default if `sameSite` isn't specified.

**Comment by Rob--W** [comment]
Thanks for the report. This reminds me of the need to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1550032 in Firefox.

**Comment by TheDcoder** [comment]
Cool, but I think we should also fix it in the extension code so that it works in current and previous versions of Firefox.

**Comment by Rob--W** [comment]
> Cool, but I think we should also fix it in the extension code so that it works in current and previous versions of Firefox.

That was the intention behind https://github.com/Rob--W/cookie-manager/commit/1c1f390c3f1c6281961470fb999fcec9e8be4003 , but I apparently made a mistake.

There should be a `!` before `chrome.cookies.SameSiteStatus.UNSPECIFIED`

https://github.com/Rob--W/cookie-manager/blob/c1d5f0597bf3347f11a9cf4999db12a30079ea27/cookie-manager.js#L1262

And although it does not really matter, the (duplicate) `selected` attribute should be removed from https://github.com/Rob--W/cookie-manager/blob/c1d5f0597bf3347f11a9cf4999db12a30079ea27/cookie-manager.html#L166

I'll fix this when I have access to my repository again. But if you'd like to submit a pull request I'm willing to merge that too.

**Comment by TheDcoder** [comment]
Ah, I see...

> But if you'd like to submit a pull request I'm willing to merge that too.

Sure, why not. I made a PR with the changes you mentioned: #54
