### ISSUE TITLE
Unable to install Cookie-Manager in Firefox for Android

### ISSUE THREAD

**Issue by PthDE** [Rob--W/cookie-manager#55]
Cookie-Manager is not offered by Firefox's Recommended Add-ons.

After surfing within Firefox under Android, the file a_cookie_manager-1.7.xpi, offered by Rob-W cannot be opened (grey'd or blue'd out). Instead, an informative link is presented (by Firefox?) to Firefox's recommended Add-ons.

Using Firefox on a Desktop (running Ubuntu) ), downloading and transporting to the Android device, then trying to open the file a_cookie_manager-1.7.xpi on that device, Android fails, by not offering Firefox as an appropriate app.

**Comment by Rob--W** [comment]
Currently, the number of supported extensions in Firefox for Android is limited. Wide support will be opened up in a few months, as announced in https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/

If you'd like to use the cookie manager before that, then you can install it using the mechanism (available to Nightly and Beta only) documented at:
- https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
- https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/

**Comment by Rob--W** [comment]
Updated in https://github.com/Rob--W/cookie-manager/commit/2d78a0a08fd2ab1ca2953b0a9e9ff047a4ca8c16
